import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7F8FC]">

        <div className="w-[260px] h-screen fixed left-0 top-0 bg-white">
          <SideBar />
        </div>

        <div className="ml-[260px] flex-1 flex flex-col">

          {/* HEADER (fixed top) */}
          <div className="h-[50px] fixed top-0 left-[260px] right-0 bg-white  z-20">
            <Header />
          </div>

          <main className="mt-[70px] p-6 min-h-screen">
            {children}
          </main>

        </div>
        
      </body>
    </html>
  );
}
